services:
  venuehub-api:
    container_name: venuehub-next
    restart: always
    image: node:20.10.0
    ports:
      - '4000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/venuehub-next
    working_dir: /usr/src/venuehub-next
    networks:
      - client-network
    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
